# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-01-11 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_auto_20210111_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregado',
            name='departamento',
            field=models.ManyToManyField(blank=True, to='clientes.Departamento'),
        ),
    ]
