# Generated by Django 5.1.4 on 2025-01-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='object_id',
            field=models.CharField(max_length=255),
        ),
    ]
