# Generated by Django 5.1.4 on 2025-01-12 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_alter_tag_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='object_id',
        ),
    ]
