# Generated by Django 3.1.6 on 2021-02-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='id',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='id',
        ),
        migrations.AddField(
            model_name='cor',
            name='id_cor',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marca',
            name='id_marca',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='id_pessoa',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='id_veiculo',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cor',
            name='cor',
            field=models.CharField(max_length=100),
        ),
    ]
