# Generated by Django 3.1.6 on 2021-02-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_veiculo_observacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_hora', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor por hora')),
                ('valor_mes', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor por mes')),
            ],
        ),
    ]
