# Generated by Django 3.1.6 on 2021-02-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_movrotativohora_movrotativomes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movrotativomes',
            name='entrada',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='movrotativomes',
            name='saida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
