# Generated by Django 3.1.6 on 2021-02-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_veiculo_proprietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='observacao',
            field=models.TextField(default='Sem Observação'),
            preserve_default=False,
        ),
    ]
