# Generated by Django 3.1.6 on 2021-02-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210215_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='categoria',
            field=models.CharField(default='B', max_length=2),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='sobrenome',
            field=models.CharField(default='Sem Sobrenome', max_length=200),
        ),
    ]
