# Generated by Django 3.1.6 on 2021-02-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210215_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(default='B', max_length=2)),
                ('descricao', models.TextField(max_length=1000)),
            ],
        ),
    ]
