# Generated by Django 3.1.6 on 2021-02-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210215_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='nome',
            new_name='marca',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='id',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='id_pessoa',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
