# Generated by Django 3.1.6 on 2021-02-15 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria'),
        ),
    ]
