# Generated by Django 3.1.6 on 2021-02-15 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_parametros'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovRotativoMes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateTimeField()),
                ('saida', models.DateTimeField(blank=True, null=True)),
                ('pago', models.BooleanField(default=False)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.veiculo')),
                ('vl_mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parametros')),
            ],
        ),
        migrations.CreateModel(
            name='MovRotativoHora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateTimeField()),
                ('saida', models.DateTimeField(blank=True, null=True)),
                ('pago', models.BooleanField(default=False)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.veiculo')),
                ('vl_hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parametros')),
            ],
        ),
    ]
